version: "3.9"
services:
  db:
    image: postgis/postgis:16-3.4
    container_name: gist-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: gist
      POSTGRES_USER: gist
      POSTGRES_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
volumes:
  db-data: