spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/gist}
    username: ${SPRING_DATASOURCE_USERNAME:gist}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${RESTART:none}
      auto_quote_keyword: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: ${REDIS_SSL:false}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: debug
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"

hospital:
  api:
    base-url: ${COMMON_API_URL:http://apis.data.go.kr/B552657/HsptlAsembySearchService}
    service-key: ${COMMON_API_SECRET:}
